### ISSUE TITLE
Sort by Timestamp incorrect when time is displayed

### ISSUE THREAD

**Issue by dhstack** [benwinding/react-admin-firebase#95]
When sorting a list view by a timestamp field, the date is sorted correctly, but the time is reversed from how the date is sorted.

**ASC**
![image](https://user-images.githubusercontent.com/2013388/77810670-0fad0e80-706c-11ea-8e23-b7ecd2d9dbbe.png)

**DESC**
![image](https://user-images.githubusercontent.com/2013388/77810690-28b5bf80-706c-11ea-9ddb-1609fef3b90d.png)

**Comment by dhstack** [comment]
Also, is there a reason we're not using the built in [`orderBy()`](https://firebase.google.com/docs/firestore/query-data/order-limit-data) that `Firebase` provides instead of the custom `sortArray()` in [arrayHelpers.ts](https://github.com/benwinding/react-admin-firebase/blob/master/src/misc/arrayHelpers.ts)?

**Comment by benwinding** [comment]
> When sorting a list view by a timestamp field, the date is sorted correctly, but the time is reversed from how the date is sorted.

That's strange, I'll have a look at that.

> Also, is there a reason we're not using the built in orderBy() that Firebase provides instead of the custom sortArray() in arrayHelpers.ts?

Yes it's weird but there are some limitations in using Firestore's sorting. The main one is pagination by numbers (1,2...) is not possible, you can only paginate by doc-references from the [limit()](https://firebase.google.com/docs/firestore/query-data/order-limit-data) function. This was also discussed heavily in issue #20

**Comment by benwinding** [comment]
Hi @dhstack 

This is a strange problem, but I think it was due to treating all fields as either a number or string. This should be fixed here 35a8745 and deployed as version `3.1.14`

If there's any issues, let me know. I've got a few unit-tests for this now, located here:
https://github.com/benwinding/react-admin-firebase/blob/35a87452f1512ace9537aec3d72a8153a2e073b3/tests/arrayHelpers.sorting.spec.ts#L18-L41

Cheers,
Ben

**Comment by dhstack** [comment]
Works for me, thanks!

**Comment by abadrangui** [comment]
Hi, I'm still having same issue at 3.2.24.

Here i've activated the sorter, but when i scroll down 
<img width="245" alt="Screen Shot 2021-11-24 at 01 52 02" src="https://user-images.githubusercontent.com/45628044/143078141-cdab5679-7a2d-4af8-ad29-48bfc558dbf0.png">

There is a sorting issue still. 
<img width="262" alt="Screen Shot 2021-11-24 at 01 52 22" src="https://user-images.githubusercontent.com/45628044/143078148-b1b622a8-4fbb-4559-a178-360ec5d26932.png">

Can u check it again pls?
